name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu
    container:
      image: node:20
    
    steps:
      - uses: actions/checkout@v3
      - with:
          node-version: 20

      - run: yarn install
      - run: yarn run build


