name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g yarn

      - run: yarn install

      - run: yarn run build

      - run: echo ${{ secrets.SSH_PUBLIC_KEY }}

      - run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - run: |
          scp -i ~/.ssh/id_rsa.pub ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:/app/
          


      