name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g yarn

      - run: yarn install

      - run: yarn run build

      - run: echo ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "mkdir -p ~/app"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dist package.json yarn.lock ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:/root/app

      - run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} "cd ~/app && yarn install"

    
      